version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=https://extends-recovery-minority-supreme.trycloudflare.com  # <-- Local machine IP where Ollama runs
      - DATABASE_URL=sqlite+aiosqlite:///./data/handwriting.db
      - OLLAMA_MODEL=llava:latest
      - OLLAMA_TIMEOUT_SECONDS=120
      - OLLAMA_TEMPERATURE=0.1
      - OLLAMA_NUM_PREDICT=2048
      - ENABLE_IMAGE_PREPROCESSING=true
    volumes:
      - backend_data:/app/data
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    environment:
      - BACKEND_URL=http://52.47.180.240:8000   # <-- Replace with your EC2 public IP to access from browser
    depends_on:
      - backend

volumes:
  backend_data:
